### ISSUE TITLE
Create table using data from the Petfinder API

### ISSUE THREAD

**Issue by JoshBogin** [CSI-280/gitgood#17]
In order to further utilize the Petfinder API, someone should set up a table using HTML that displays information from the API like a table of pets.

**Comment by PointlessVenture** [comment]
You mention that you want to add a table of animals- If this is what we want to do, we should change the issue to reflect such- If we just want to utilize *something*, we should plan out what that is.

**Comment by JoshBogin** [comment]
Yeah, I know its a good idea to start using the API further but I wasn't exactly sure how so it was a vague idea to start.

**Comment by JoshBogin** [comment]
I think it is more clear now.

**Comment by PointlessVenture** [comment]
Indeed.

**Comment by PointlessVenture** [comment]
Issue Found: The Petfinder API requires the ability to make requests: 

(https://www.petfinder.com/developers/v2/docs/#using-the-api)

This *usually*requires jquery or ajax to do, so we will need to add one to the project before this can be done. This isn't difficult, but i'll need to talk to people about which we prefer.

**Comment by PointlessVenture** [comment]
I have little Idea how to do this. The documentation requests a cURL command be used- but i know not how to do that or how to convert it into a form javascript can understand.

**Comment by chrisbendel** [comment]
https://github.com/petfinder-com/petfinder-js-sdk#install

@PointlessVenture you can use this library, NPM install it and use it in this way:

```
Usage (TypeScript/ES6 Module)
import { Client } from "@petfinder/petfinder-js";

const client = new Client({apiKey: "my-api-key", secret: "my-api-secret"});

client.animal.search()
    .then(function (response) {
        // Do something with `response.data.animals`
    })
    .catch(function (error) {
        // Handle the error
    });
```

there are docs here on what endpoints are supported/available: https://github.com/petfinder-com/petfinder-js-sdk/tree/master/docs

No need for jquery/ajax, and this library will handle authentication for you when you initialize it with the auth token/secret
