### ISSUE TITLE
Plan styling for website

### ISSUE THREAD

**Issue by lhvinton** [CSI-280/gitgood#18]
It is a good idea to start planning what we want the style of the website to start looking like. Basic HTML is not super exciting to look at.

**Comment by wesbeard** [comment]
I plan on setting up the CSS files with basic styling and applying styling to the new features created from the other issues.

**Comment by wesbeard** [comment]
I set up the project in vue and created some basic div, button, and font styling for future development. I can add styling as more components are added.

**Comment by wesbeard** [comment]
Default styling with fonts and design has been set up in Vue. Header and footer now carry over on page change and components resize well.
