### ISSUE TITLE
Create framework for users to enter a location

### ISSUE THREAD

**Issue by PointlessVenture** [CSI-280/gitgood#23]
If we're going to sort pets by where they are located, we're going to need some way for us to determine where the user is located- either by using location serves or by asking the user to enter manually.

**Comment by lhvinton** [comment]
@PointlessVenture Is this issue just about getting the location data or does it involve using that data to do other stuff as well?

**Comment by PointlessVenture** [comment]
I only meant this to imply getting the data, not necessarily doing anything with it yet.

**Comment by thomasszp** [comment]
I just made it detect and record location data from the user, would be pretty easy to embed a map of the geolocation as a next step though.

**Comment by thomasszp** [comment]
Issue closed by pull#40
