### ISSUE TITLE
Implement styling for page menu

### ISSUE THREAD

**Issue by wesbeard** [CSI-280/gitgood#33]
We should integrate the menu system into our current design

**Comment by wesbeard** [comment]
We may want to create a separate section that stays between pages to act as the navbar so we don't create new buttons for every page.

**Comment by collin-westgate** [comment]
By "separate section" do you mean one piece of code that every page uses like a component, or just to have the nav bar be standardized between the pages so it _appears_ to be a separate piece at the top of the page? I tried setting it up as a vue component and didn't have any luck.

**Comment by wesbeard** [comment]
I think it would be best if it was a separate component so that if we want to change it it'll change over all of the pages.
