### ISSUE TITLE
Get and display info from the API on the second page

### ISSUE THREAD

**Issue by collin-westgate** [CSI-280/gitgood#35]
We should get at least something from the API to show on our second page, this can be up to you. Maybe scrolling pictures of dogs/cats/animals or even just an example pet with its name, breed, etc. If we end up adding other pages, we may also want to extend this to them as well.

**Comment by PointlessVenture** [comment]
How exactly does this differ from #17 ? I believe this is what i am currently trying to do.

**Comment by collin-westgate** [comment]
It's essentially just to add more stuff from the API on the second page we made so that we can get to different info using the nav bar.
