### ISSUE TITLE
Decide content for "Other" page

### ISSUE THREAD

**Issue by JoshBogin** [CSI-280/gitgood#39]
I added a few pages in the last merge and now we need to start filling pages in because the website is going to be finished soon. The cat and dog pages are pretty simple and someone can make an issue to add content to them. But I want someone to figure out what should go on the other page, in terms of what pets and what content.

**Comment by PointlessVenture** [comment]
Would it make sense to just add any animals that were neither dogs, nor cats?

**Comment by PointlessVenture** [comment]
Resolved in #45.
