### ISSUE TITLE
Create Introduction on the Homepage

### ISSUE THREAD

**Issue by PointlessVenture** [CSI-280/gitgood#42]
Something simple to do, but the homepage could use some content, particularly if we're going to sort by animals.

**Comment by wesbeard** [comment]
I'll work on displaying some content using the Petfinder API and add some basic home page info.

**Comment by PointlessVenture** [comment]
If this done, link the pull request here, then close the issue and add the closed tag.

**Comment by wesbeard** [comment]
https://github.com/CSI-280/gitgood/pull/46
