### ISSUE TITLE
Actually implement a feature with new geodata

### ISSUE THREAD

**Issue by thomasszp** [CSI-280/gitgood#43]
Now that we actually have the geographic coordinates of the user, we should be able to embed a google map that can display that information. If possible maybe also let the user add their own location if they dont want to use location services.

This could be further expanded on down the line if we ever tried to have location-based search fields for animals in a vicinity.

**Comment by wesbeard** [comment]
We might need to use this for the dogs/cats page and i might use it to put a map on the home page.

**Comment by thomasszp** [comment]
Ok i've figured out how to embed a google map using the geolocation data from last week.

Only thing left to do is figure out vue and our where our homepage is.
